"""Generate compact Markdown API references for CadQuery by introspection.

Usage: python gen_api_reference.py OUTPUT_DIR

Emits:
  api-workplane.md         Workplane methods, selectors, exporters/importers
  api-sketch-assembly.md   Sketch, Assembly, Location/Vector/Plane, free functions
"""

import inspect
import re
import sys
from pathlib import Path

import cadquery as cq


def first_para(doc: str | None, max_chars: int = 220) -> str:
    if not doc:
        return ""
    doc = inspect.cleandoc(doc)
    # first paragraph, collapsed to one line
    para = doc.split("\n\n")[0]
    line = " ".join(para.split())
    # cut at ":param" style tails if the paragraph runs into them
    line = re.split(r":param|:return|:rtype|:raises", line)[0].strip()
    if len(line) > max_chars:
        line = line[: max_chars - 1].rstrip() + "…"
    return line


def sig_of(obj) -> str:
    try:
        sig = str(inspect.signature(obj))
    except (ValueError, TypeError):
        return "(...)"
    # drop noisy typing module prefixes
    sig = sig.replace("typing.", "").replace("cadquery.occ_impl.geom.", "")
    sig = re.sub(r"\bcadquery\.(\w+\.)*", "", sig)
    if len(sig) > 300:
        sig = sig[:299] + "…"
    return sig


def methods_md(cls, title: str, skip: set[str] | None = None) -> str:
    skip = skip or set()
    out = [f"## {title}\n"]
    cls_doc = first_para(cls.__doc__)
    if cls_doc:
        out.append(f"{cls_doc}\n")
    names = [
        n
        for n, m in inspect.getmembers(cls, callable)
        if not n.startswith("_") and n not in skip and n in cls.__dict__ or
           (not n.startswith("_") and n not in skip and any(n in b.__dict__ for b in cls.__mro__[1:-1]))
    ]
    for name in sorted(set(names)):
        member = getattr(cls, name)
        if not callable(member):
            continue
        out.append(f"- `{name}{sig_of(member)}`")
        d = first_para(getattr(member, "__doc__", None))
        if d:
            out.append(f"  - {d}")
    out.append("")
    return "\n".join(out)


def functions_md(module, title: str, only: list[str] | None = None) -> str:
    out = [f"## {title}\n"]
    for name, fn in sorted(inspect.getmembers(module, inspect.isfunction)):
        if name.startswith("_"):
            continue
        if only is not None and name not in only:
            continue
        out.append(f"- `{name}{sig_of(fn)}`")
        d = first_para(fn.__doc__)
        if d:
            out.append(f"  - {d}")
    out.append("")
    return "\n".join(out)


def main(out_dir: Path) -> None:
    ver = cq.__version__
    header = (
        "<!-- AUTO-GENERATED by gen_api_reference.py against cadquery "
        f"{ver}. Do not edit by hand; regenerate instead. -->\n"
    )

    # ---- api-workplane.md ----
    parts = [header, f"# CadQuery {ver} — Workplane API reference\n"]
    parts.append(methods_md(cq.Workplane, "cq.Workplane"))

    from cadquery import selectors

    sel = ["## String selectors (used by faces()/edges()/vertices()/solids())\n"]
    sel.append(
        "Filters: `+Z -Z +X …` (direction), `>Z <Z` (max/min in direction), "
        "`>Z[n]` (nth in direction), `|Z` (parallel), `#Z` (perpendicular), "
        "`%Plane %Cylinder %Circle %Line` (geom type). "
        "Combine: `and`, `or`, `not`, `exc`, parentheses.\n"
    )
    sel.append("Selector classes (for programmatic use):\n")
    for name, cls in sorted(inspect.getmembers(selectors, inspect.isclass)):
        if cls.__module__ != selectors.__name__ or name.startswith("_"):
            continue
        d = first_para(cls.__doc__)
        sel.append(f"- `selectors.{name}` — {d}")
    parts.append("\n".join(sel) + "\n")

    from cadquery import exporters, importers

    parts.append(functions_md(exporters, "cq.exporters"))
    parts.append(functions_md(importers, "cq.importers"))
    (out_dir / "api-workplane.md").write_text("\n".join(parts))

    # ---- api-sketch-assembly.md ----
    parts = [header, f"# CadQuery {ver} — Sketch / Assembly / geometry reference\n"]
    parts.append(methods_md(cq.Sketch, "cq.Sketch"))
    parts.append(methods_md(cq.Assembly, "cq.Assembly"))

    for cls, title in [
        (cq.Location, "cq.Location"),
        (cq.Vector, "cq.Vector"),
        (cq.Plane, "cq.Plane"),
    ]:
        parts.append(methods_md(cls, title))

    try:
        from cadquery import func as cq_func

        parts.append(functions_md(cq_func, "cadquery.func (free function API)"))
    except ImportError:
        pass
    (out_dir / "api-sketch-assembly.md").write_text("\n".join(parts))

    for f in ("api-workplane.md", "api-sketch-assembly.md"):
        p = out_dir / f
        print(f"{f}: {len(p.read_text().splitlines())} lines, {len(p.read_text())} chars")


if __name__ == "__main__":
    out = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(".")
    out.mkdir(parents=True, exist_ok=True)
    main(out)
